"""empty message

Revision ID: 12364f1c1146
Revises: 9430b0bbc701
Create Date: 2021-03-17 16:51:18.575280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12364f1c1146'
down_revision = '9430b0bbc701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials_from_field', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.drop_column('quests', 'eng_source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('eng_source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_column('materials_from_field', 'id')
    # ### end Alembic commands ###
