"""empty message

Revision ID: 143ec5b9752d
Revises: ec114e6b5254
Create Date: 2021-03-21 02:05:24.455888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '143ec5b9752d'
down_revision = 'ec114e6b5254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hit_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_name', sa.String(length=50), nullable=True),
    sa.Column('part', sa.String(length=50), nullable=True),
    sa.Column('slash', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('shot', sa.Integer(), nullable=True),
    sa.Column('fire', sa.Integer(), nullable=True),
    sa.Column('water', sa.Integer(), nullable=True),
    sa.Column('thunder', sa.Integer(), nullable=True),
    sa.Column('ice', sa.Integer(), nullable=True),
    sa.Column('dragon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_name'], ['monsters.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('materials_from_monster', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('materials_from_monster', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials_from_monster', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('materials_from_monster', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_table('hit_data')
    # ### end Alembic commands ###
