"""empty message

Revision ID: 168a19f7a2da
Revises: cd1eebe6a7e5
Create Date: 2021-03-14 00:44:36.172099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168a19f7a2da'
down_revision = 'cd1eebe6a7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('eng_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'eng_source')
    # ### end Alembic commands ###
