"""empty message

Revision ID: 35ccd7a34347
Revises: 12364f1c1146
Create Date: 2021-03-17 16:59:10.702600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35ccd7a34347'
down_revision = '12364f1c1146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.add_column('materials_from_monster', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('materials_from_monster', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('materials_from_monster', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials_from_monster', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('materials_from_monster', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.drop_column('materials_from_monster', 'id')
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    # ### end Alembic commands ###
