"""empty message

Revision ID: 393860141b7f
Revises: dd8854b74f2b
Create Date: 2021-03-14 08:59:15.521051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '393860141b7f'
down_revision = 'dd8854b74f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials_from_monster',
    sa.Column('monster_name', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('quest_source', sa.String(length=50), nullable=True),
    sa.Column('monster_part', sa.String(length=50), nullable=True),
    sa.Column('drop_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_name'], ['materials.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_name'], ['monsters.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monster_name', 'material_name')
    )
    op.create_table('materials_from_quest',
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('material_count', sa.Integer(), nullable=True),
    sa.Column('drop_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_name'], ['materials.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quest_id', 'material_name')
    )
    op.alter_column('materials', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.create_unique_constraint(None, 'materials', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='unique')
    op.alter_column('materials', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.drop_table('materials_from_quest')
    op.drop_table('materials_from_monster')
    # ### end Alembic commands ###
