"""empty message

Revision ID: 571a64c857c5
Revises: aae8495f37b9
Create Date: 2021-03-14 01:07:38.236701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571a64c857c5'
down_revision = 'aae8495f37b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hit_data',
    sa.Column('monster_name', sa.String(length=50), nullable=False),
    sa.Column('part', sa.String(length=50), nullable=False),
    sa.Column('slash', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('shot', sa.Integer(), nullable=True),
    sa.Column('fire', sa.Integer(), nullable=True),
    sa.Column('water', sa.Integer(), nullable=True),
    sa.Column('thunder', sa.Integer(), nullable=True),
    sa.Column('ice', sa.Integer(), nullable=True),
    sa.Column('dragon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_name'], ['monsters.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monster_name', 'part')
    )
    op.create_table('weak_elements',
    sa.Column('monster_name', sa.String(length=50), nullable=False),
    sa.Column('element', sa.String(length=5), nullable=False),
    sa.Column('effectiveness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_name'], ['monsters.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monster_name', 'element')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weak_elements')
    op.drop_table('hit_data')
    # ### end Alembic commands ###
