"""empty message

Revision ID: 9430b0bbc701
Revises: 7f5821470d43
Create Date: 2021-03-17 16:34:21.935586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9430b0bbc701'
down_revision = '7f5821470d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('field_name', sa.String(length=50), nullable=True))
    op.drop_constraint('quests_ibfk_1', 'quests', type_='foreignkey')
    op.create_foreign_key(None, 'quests', 'fields', ['field_name'], ['name'], ondelete='SET NULL')
    op.drop_column('quests', 'field_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('field_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.create_foreign_key('quests_ibfk_1', 'quests', 'fields', ['field_id'], ['id'], ondelete='SET NULL')
    op.drop_column('quests', 'field_name')
    # ### end Alembic commands ###
