"""empty message

Revision ID: a1379f89e099
Revises: a142763941d6
Create Date: 2021-03-14 01:01:58.125389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1379f89e099'
down_revision = 'a142763941d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_monsters',
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('monster_name', sa.String(length=50), nullable=False),
    sa.Column('monster_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_name'], ['monsters.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quest_id', 'monster_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_monsters')
    # ### end Alembic commands ###
