"""empty message

Revision ID: cd1eebe6a7e5
Revises: 
Create Date: 2021-03-13 23:07:42.088983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1eebe6a7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('eng_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mhr_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('jap_name', sa.String(length=50), nullable=True),
    sa.Column('is_large', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=20), nullable=True),
    sa.Column('monster_class', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hit_data',
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=50), nullable=False),
    sa.Column('slash', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('shot', sa.Integer(), nullable=True),
    sa.Column('fire', sa.Integer(), nullable=True),
    sa.Column('water', sa.Integer(), nullable=True),
    sa.Column('thunder', sa.Integer(), nullable=True),
    sa.Column('ice', sa.Integer(), nullable=True),
    sa.Column('dragon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monster_id', 'part')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_key', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_star', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(length=200), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weak_elements',
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('element', sa.String(length=5), nullable=False),
    sa.Column('effectiveness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monster_id', 'element')
    )
    op.create_table('quest_monsters',
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('monster_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quest_id', 'monster_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_monsters')
    op.drop_table('weak_elements')
    op.drop_table('quests')
    op.drop_table('hit_data')
    op.drop_table('monsters')
    op.drop_table('mhr_news')
    op.drop_table('materials')
    op.drop_table('fields')
    # ### end Alembic commands ###
