"""empty message

Revision ID: ec114e6b5254
Revises: 60e6a17ad7cb
Create Date: 2021-03-21 02:01:37.813943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec114e6b5254'
down_revision = '60e6a17ad7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hit_data', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('hit_data', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('hit_data', 'part',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('materials_from_monster', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('materials_from_monster', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials_from_monster', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('materials_from_monster', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('materials_from_field', 'material_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('materials_from_field', 'field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('hit_data', 'part',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('hit_data', 'monster_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_column('hit_data', 'id')
    # ### end Alembic commands ###
